=== dashnine/PaperBlossoms/PaperBlossoms/data/json_schema/armor.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Armor",
    "description": "List of armor",
    "type": "array",
    "items": {
        "description": "Armor",
        "type": "object",
        "properties": {
            "name": {
                "description": "Name of armor",
                "type": "string"
            },
            "reference": {
                "description": "Page reference for armor",
                "type": "object",
                "properties": {
                    "book": {
                        "description": "Book in which reference can be found",
                        "type": "string",
                        "enum": [
                            "GMK",
                            "EE",
                            "SL",
                            "Mantis",
                            "Core",
                            "CoS",
                            "PoW"
                        ]
                    },
                    "page": {
                        "description": "Page on which reference can be found",
                        "type": "integer"
                    }
                },
                "required": [
                    "book",
                    "page"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Page reference for armor",
                        "body": {
                            "book": "$1",
                            "page": "^$2"
                        }
                    }
                ]
            },
            "resistance_values": {
                "description": "List of resistance values",
                "type": "array",
                "default": [],
                "items": {
                    "description": "Resistance value",
                    "type": "object",
                    "properties": {
                        "category": {
                            "description": "Resistance value category",
                            "type": "string",
                            "enum": [
                                "Supernatural",
                                "Physical"
                            ]
                        },
                        "value": {
                            "description": "Resistance numeric value",
                            "type": "integer"
                        }
                    },
                    "required": [
                        "category",
                        "value"
                    ],
                    "defaultSnippets": [
                        {
                            "label": "New Resistance value",
                            "body": {
                                "category": "$1",
                                "value": "^$2"
                            }
                        }
                    ]
                }
            },
            "qualities": {
                "description": "List of armor qualities",
                "type": "array",
                "default": [],
                "items": {
                    "description": "Armor quality",
                    "type": "string",
                    "enum": [
                        "Cumbersome",
                        "Mundane",
                        "Sacred",
                        "Wargear",
                        "Durable",
                        "Damaged",
                        "Forbidden",
                        "Prepare",
                        "Subtle",
                        "Destroyed",
                        "Concealable",
                        "Razor-edged",
                        "Ceremonial",
                        "Snaring",
                        "Resplendent",
                        "Unholy"
                    ]
                }
            },
            "rarity": {
                "description": "Rarity level",
                "type": "integer"
            },
            "price": {
                "description": "Price of armor",
                "type": "object",
                "properties": {
                    "value": {
                        "description": "Numeric value",
                        "type": "integer"
                    },
                    "unit": {
                        "description": "Monetary unit",
                        "type": "string",
                        "enum": [
                            "bu",
                            "zeni",
                            "koku"
                        ]
                    }
                },
                "required": [
                    "value",
                    "unit"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Price of armor",
                        "body": {
                            "value": "^$1",
                            "unit": "$2"
                        }
                    }
                ]
            }
        },
        "required": [
            "name",
            "reference",
            "resistance_values",
            "qualities",
            "rarity",
            "price"
        ],
        "defaultSnippets": [
            {
                "label": "New Armor",
                "body": {
                    "name": "$1",
                    "reference": "^$2",
                    "resistance_values": "^[$3]",
                    "qualities": "^[$4]",
                    "rarity": "^$5",
                    "price": "^$6"
                }
            }
        ]
    }
}

=== dashnine/PaperBlossoms/PaperBlossoms/data/json/armor.json
[
    {
        "name": "Sleeping Garb",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [],
        "qualities": [],
        "rarity": 2,
        "price": {
            "value": 1,
            "unit": "koku"
        }
    },
    {
        "name": "Common Clothes",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 1
            }
        ],
        "qualities": ["Mundane"],
        "rarity": 1,
        "price": {
            "value": 1,
            "unit": "bu"
        }
    },
    {
        "name": "Inconspicuous Garb",
        "reference": {
            "book": "Core",
            "page": 80
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 1
            }
        ],
        "qualities": ["Mundane"],
        "rarity": 1,
        "price": {
            "value": 1,
            "unit": "bu"
        }
    },
    {
        "name": "Ceremonial Clothes",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 1
            }
        ],
        "qualities": ["Ceremonial", "Resplendent"],
        "rarity": 4,
        "price": {
            "value": 1,
            "unit": "koku"
        }
    },
    {
        "name": "Sanctified Robes",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 1
            },
            {
                "category": "Supernatural",
                "value": 3
            }
        ],
        "qualities": ["Ceremonial"],
        "rarity": 7,
        "price": {
            "value": 4,
            "unit": "koku"
        }
    },
    {
        "name": "Traveling Clothes",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 2
            }
        ],
        "qualities": ["Durable", "Mundane", "Subtle"],
        "rarity": 2,
        "price": {
            "value": 2,
            "unit": "bu"
        }
    },
    {
        "name": "Concealed Armor",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 2
            }
        ],
        "qualities": ["Concealable"],
        "rarity": 4,
        "price": {
            "value": 5,
            "unit": "koku"
        }
    },
    {
        "name": "Ashigaru Armor",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 3
            }
        ],
        "qualities": ["Wargear"],
        "rarity": 3,
        "price": {
            "value": 5,
            "unit": "koku"
        }
    },
    {
        "name": "Lacquered Armor",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 4
            }
        ],
        "qualities": ["Ceremonial", "Cumbersome", "Wargear"],
        "rarity": 6,
        "price": {
            "value": 25,
            "unit": "koku"
        }
    },
    {
        "name": "Plated Armor",
        "reference": {
            "book": "Core",
            "page": 239
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 5
            }
        ],
        "qualities": ["Cumbersome", "Durable", "Wargear"],
        "rarity": 8,
        "price": {
            "value": 40,
            "unit": "koku"
        }
    },
    {
        "name": "ÅŒ-yoroi",
        "reference": {
            "book": "SL",
            "page": 105
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 6
            }
        ],
        "qualities": ["Cumbersome", "Resplendent", "Wargear"],
        "rarity": 8,
        "price": {
            "value": 60,
            "unit": "koku"
        }
    },
    {
        "name": "Tatami Gusoku",
        "reference": {
            "book": "SL",
            "page": 106
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 3
            }
        ],
        "qualities": ["Wargear"],
        "rarity": 4,
        "price": {
            "value": 7,
            "unit": "koku"
        }
    },
    {
        "name": "Tosei-Gusoku",
        "reference": {
            "book": "SL",
            "page": 106
        },
        "resistance_values": [
            {
                "category": "Physical",
                "value": 4
            }
        ],
        "qualities": ["Cumbersome", "Durable", "Wargear"],
        "rarity": 8,
        "price": {
            "value": 50,
            "unit": "koku"
        }
    }
]
