=== dashnine/PaperBlossoms/PaperBlossoms/data/json_schema/personal_effects.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Personal effects",
    "description": "List of personal effects",
    "type": "array",
    "items": {
        "description": "Personal effect",
        "type": "object",
        "properties": {
            "name": {
                "description": "Name of personal effect",
                "type": "string"
            },
            "reference": {
                "description": "Page reference for personal effect",
                "type": "object",
                "properties": {
                    "book": {
                        "description": "Book in which reference can be found",
                        "type": "string",
                        "enum": [
                            "CoS",
                            "Core",
                            "EE",
                            "GMK",
                            "Mantis",
                            "PoW",
                            "SL"
                        ]
                    },
                    "page": {
                        "description": "Page on which reference can be found",
                        "type": "integer"
                    }
                },
                "required": [
                    "book",
                    "page"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Page reference for personal effect",
                        "body": {
                            "book": "$1",
                            "page": "^$2"
                        }
                    }
                ]
            },
            "price": {
                "description": "Price of personal effect",
                "type": "object",
                "properties": {
                    "value": {
                        "description": "Numeric value",
                        "type": "integer"
                    },
                    "unit": {
                        "description": "Monetary unit",
                        "type": "string",
                        "enum": [
                            "bu",
                            "koku",
                            "zeni"
                        ]
                    }
                },
                "required": [
                    "value",
                    "unit"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Price of personal effect",
                        "body": {
                            "value": "^$1",
                            "unit": "$2"
                        }
                    }
                ]
            },
            "rarity": {
                "description": "Rarity level",
                "type": "integer"
            },
            "qualities": {
                "description": "Item qualities",
                "type": "array",
                "items": {
                    "description": "Item quality",
                    "type": "string",
                    "enum": [
                        "Ceremonial",
                        "Concealable",
                        "Cumbersome",
                        "Damaged",
                        "Destroyed",
                        "Durable",
                        "Forbidden",
                        "Mundane",
                        "Prepare",
                        "Razor-edged",
                        "Resplendent",
                        "Sacred",
                        "Snaring",
                        "Subtle",
                        "Unholy",
                        "Wargear"
                    ]
                }
            }
        },
        "required": [
            "name",
            "reference"
        ],
        "defaultSnippets": [
            {
                "label": "New Personal effect",
                "body": {
                    "name": "$1",
                    "reference": "^$2",
                    "price": "^$3",
                    "rarity": "^$4"
                }
            }
        ]
    }
}

=== dashnine/PaperBlossoms/PaperBlossoms/data/json/personal_effects.json
[
    {
        "name": "Bottle of Sake",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 1
    },
    {
        "name": "Bowyer's Kit",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 2,
            "unit": "bu"
        },
        "rarity": 1
    },
    {
        "name": "Calligraphy Set",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 3
    },
    {
        "name": "Chopsticks",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Daishō Stand",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "koku"
        },
        "rarity": 4
    },
    {
        "name": "Dice and Cup",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 25,
            "unit": "zeni"
        },
        "rarity": 2
    },
    {
        "name": "Playing Cards",
        "reference": {
            "book": "Mantis",
            "page": 5
        },
        "price": {
            "value": 25,
            "unit": "zeni"
        },
        "rarity": 2
    },
    {
        "name": "Divination Kit",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 4
    },
    {
        "name": "Finger of Jade",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "koku"
        },
        "rarity": 6
    },
    {
        "name": "Games",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 3
    },
    {
        "name": "Kubi Bukuro",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 2,
            "unit": "zeni"
        },
        "rarity": 2,
        "qualities": ["Wargear"]
    },
    {
        "name": "Lucky Cricket",
        "reference": {
            "book": "Core",
            "page": 242
        },
        "price": {
            "value": 4,
            "unit": "bu"
        },
        "rarity": 4
    },
    {
        "name": "Medicine Kit",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 3
    },
    {
        "name": "Musical Instrument (common)",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Musical Instrument (fine)",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 6
    },
    {
        "name": "Omamori",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Boon of Fukurokujin [Omamori]",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Boon of Bishamon [Omamori]",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Boon of Benten [Omamori]",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Personal Seal or Chop",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 4,
            "unit": "bu"
        },
        "rarity": 6,
        "qualities": ["Ceremonial"]
    },
    {
        "name": "Pillow Book",
        "reference": {
            "book": "Core",
            "page": 243
        },
        "price": {
            "value": 3,
            "unit": "zeni"
        },
        "rarity": 2
    },
    {
        "name": "Poison (per vial)",
        "reference": 
        {
            "book": "Core",
            "page": 244
        },
        "price": {
            "value": 30,
            "unit": "zeni"
        },
        "rarity": 5,
        "qualities": ["Forbidden"]
    },
    {
        "name": "Quiver of Arrows",
        "reference": 
        {
            "book": "Core",
            "page": 244
        },
        "price": {
            "value": 20,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Quiver of Bolts",
        "reference": 
        {
            "book": "Core",
            "page": 59
        },
        "price": {
            "value": 20,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Rope (per foot, cheap)",
        "reference": {
            "book": "Core",
            "page": 244
        },
        "price": {
            "value": 5,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Rope (per foot, expensive)",
        "reference": {
            "book": "Core",
            "page": 244
        },
        "price": {
            "value": 20,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Rope (twenty feet)",
        "reference": {
            "book": "Mantis",
            "page": 5
        },
        "price": {
            "value": 2,
            "unit": "koku"
        },
        "rarity": 1
    },
    {
        "name": "Sake Cup",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 2
    },
    {
        "name": "Spices (common)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 5
    },
    {
        "name": "Spices (rare)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 5,
            "unit": "bu"
        },
        "rarity": 7
    },
    {
        "name": "Sweets (per four servings)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 1
    },
    {
        "name": "Tattoo Needles (per set)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "bu"
        },
        "rarity": 4
    },
    {
        "name": "Tea Set (portable)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "koku"
        },
        "rarity": 6
    },
    {
        "name": "Tent (chomchong)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 20,
            "unit": "koku"
        },
        "rarity": 7
    },
    {
        "name": "Tent (small)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "koku"
        },
        "rarity": 3
    },
    {
        "name": "Tent (yurt)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 10,
            "unit": "koku"
        },
        "rarity": 5
    },
    {
        "name": "Traveling Rations (per meal)",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 5,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Umbrella",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 2,
            "unit": "bu"
        },
        "rarity": 4
    },
    {
        "name": "Whetstone",
        "reference": {
            "book": "Core",
            "page": 245
        },
        "price": {
            "value": 1,
            "unit": "zeni"
        },
        "rarity": 1
    },
    {
        "name": "Scroll Satchel",
        "reference": {
            "book": "Core",
            "page": 314
        }
    },
    {
        "name": "Makeup Kit",
        "reference": {
            "book": "Core",
            "page": 60
        }
    },
    {
        "name": "Attendant",
        "reference": {
            "book": "Core",
            "page": 64
        }
    },
    {
        "name": "Rokugani Pony",
        "reference": {
            "book": "Core",
            "page": 326
        }
    },
    {
        "name": "Unicorn Warhorse",
        "reference": {
            "book": "Core",
            "page": 326
        }
    },
    {
        "name": "Utaku Steed",
